name: checkme
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_hooks: ^0.20.3
  firebase_core: ^2.18.0
  cloud_firestore: ^4.15.1
  cupertino_icons: ^1.0.8
  device_preview: 1.2.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/user.png
